AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pagerduty-to-jira

Globals:
  Function:
    MemorySize: 256
    Runtime: python3.7
    Timeout: 15

Parameters:
  Stage:
    Type: String
    Description: Stage to deploy
    Default: dev

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors: "'*'"

  EscalateToPagerDutyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pd2jira_function
      Handler: pd2jira/escalate_to_pd.lambda_handler
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /escalateToPD
            Method: POST
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ssm:GetParametersByPath'
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pagerduty-to-jira/${Stage}"

  JiraToPagerDutyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pd2jira_function
      Handler: pd2jira/jira_event.lambda_handler
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /jira2pd/
            Method: POST
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:Query'
                - 'dynamodb:UpdateItem'
              Resource: 
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${IssueMappingTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserMappingTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OrganizationMappingTable}"
            - Effect: Allow
              Action:
                - 'ssm:GetParametersByPath'
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pagerduty-to-jira/${Stage}"

  PagerDutyToJiraFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pd2jira_function
      Handler: pd2jira/pd_event.lambda_handler
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /pd2jira
            Method: POST
        KeepWarmScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:Query'
                - 'dynamodb:UpdateItem'
              Resource: 
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${IssueMappingTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${UserMappingTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${OrganizationMappingTable}"
            - Effect: Allow
              Action:
                - 'ssm:GetParametersByPath'
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/pagerduty-to-jira/${Stage}"

  # SAM doesn't support attribute definitions yet, which kind of sucks. But our use cases are so simple that it
  # doesn't really matter that we won't have well-typed fields.
  IssueMappingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: incidentid
        Type: String 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: True
      TableName: !Sub "PagerDutyToJira-IssueMapping-${Stage}"

  UserMappingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: pd_email
        Type: String 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: True
      TableName: !Sub "PagerDutyToJira-UserMapping-${Stage}"

  OrganizationMappingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: pd_service
        Type: String 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: True
      TableName: !Sub "PagerDutyToJira-OrganizationMapping-${Stage}"

  DynamoDBEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pagerduty-to-jira/${Stage}/DYNAMODB_ENDPOINT"
      Type: String
      Value: https://dynamodb.us-east-1.amazonaws.com

  DynamoDBRegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pagerduty-to-jira/${Stage}/DYNAMODB_REGION"
      Type: String
      Value: !Ref AWS::Region

  DynamoDBIssueTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pagerduty-to-jira/${Stage}/DYNAMODB_ISSUE_TABLE"
      Type: String
      Value: !Ref IssueMappingTable

  DynamoDBUserTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pagerduty-to-jira/${Stage}/DYNAMODB_USER_TABLE"
      Type: String
      Value: !Ref UserMappingTable

  DynamoDBOrganizationTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/pagerduty-to-jira/${Stage}/DYNAMODB_ORGANIZATION_TABLE"
      Type: String
      Value: !Ref OrganizationMappingTable

Outputs:
  PagerDutyToJiraFunction:
    Description: "Lambda ARN"
    Value: !GetAtt PagerDutyToJiraFunction.Arn
  PagerDutyToJiraFunctionIamRole:
    Description: "Lambda IAM Role"
    Value: !GetAtt PagerDutyToJiraFunctionRole.Arn